/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_morkato_mcisid_McisidNative */

#ifndef _Included_org_morkato_mcisid_McisidNative
#define _Included_org_morkato_mcisid_McisidNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_morkato_mcisid_McisidNative
 * Method:    getIdentifier
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_org_morkato_mcisid_McisidNative_getIdentifier
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_morkato_mcisid_McisidNative
 * Method:    getVersionStrategy
 * Signature: (Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_org_morkato_mcisid_McisidNative_getVersionStrategy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_morkato_mcisid_McisidNative
 * Method:    getLookup
 * Signature: (C)B
 */
JNIEXPORT jbyte JNICALL Java_org_morkato_mcisid_McisidNative_getLookup
  (JNIEnv *, jclass, jchar);

#ifdef __cplusplus
}
#endif
#endif
