/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_morkato_mcisid_Mcisidv1Native */

#ifndef _Included_org_morkato_mcisid_Mcisidv1Native
#define _Included_org_morkato_mcisid_Mcisidv1Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_morkato_mcisid_Mcisidv1Native
 * Method:    nextValue
 * Signature: (Ljava/lang/Class;Lorg/morkato/mcisid/Mcisidv1Sequence;J)I
 */
JNIEXPORT jint JNICALL Java_org_morkato_mcisid_Mcisidv1Native_nextValue
  (JNIEnv *, jclass, jclass, jobject, jlong);

/*
 * Class:     org_morkato_mcisid_Mcisidv1Native
 * Method:    resetSequence
 * Signature: (Ljava/lang/Class;Lorg/morkato/mcisid/Mcisidv1Sequence;)V
 */
JNIEXPORT void JNICALL Java_org_morkato_mcisid_Mcisidv1Native_resetSequence
  (JNIEnv *, jclass, jclass, jobject);

/*
 * Class:     org_morkato_mcisid_Mcisidv1Native
 * Method:    isValidId
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_morkato_mcisid_Mcisidv1Native_isValidId
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_morkato_mcisid_Mcisidv1Native
 * Method:    getModelType
 * Signature: ([B)B
 */
JNIEXPORT jbyte JNICALL Java_org_morkato_mcisid_Mcisidv1Native_getModelType
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_morkato_mcisid_Mcisidv1Native
 * Method:    getInstantCreated
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_morkato_mcisid_Mcisidv1Native_getInstantCreated
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_morkato_mcisid_Mcisidv1Native
 * Method:    getSequenceValue
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_morkato_mcisid_Mcisidv1Native_getSequenceValue
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
